apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  serviceAccountName: demo-sa
  containers:
  - image: alpine
    command:
      - cat
    tty: true
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always  
